SymbolMissingFromElfError: fix garbage output.
SymbolMissingFromElfError: fix output for symbols removed from source elf file
but needed to export accordingly by .def